### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by jj101k** [jj101k/php-lint#26]
```
  test sync
    ⚡ TypeError: Path must be a string. Received null
        at assertPath (path.js:28:11)
        at Object.dirname (path.js:1359:5)
        at FileContext.get directory [as directory] (/Users/jimdriscoll/Public/php-lint/src/lib/file-context.js:24:34)
        at Context.set fileContext [as fileContext] (/Users/jimdriscoll/Public/php-lint/src/lib/context.js:136:36)
        at new Context (/Users/jimdriscoll/Public/php-lint/src/lib/context.js:96:26)
        at Lint.checkUncached (/Users/jimdriscoll/Public/php-lint/src/lib/lint.js:80:13)
        at Lint.check (/Users/jimdriscoll/Public/php-lint/src/lib/lint.js:67:25)
        at Function.check (/Users/jimdriscoll/Public/php-lint/src/lib/lint.js:106:22)
        at Function.checkSourceCodeSync (/Users/jimdriscoll/Public/php-lint/src/lib/php-lint.js:101:21)
        at exports.test sync (/Users/jimdriscoll/Public/php-lint/test/test-all.js:44:26)
```

**Comment by jj101k** [comment]
```
commit dbb1fd2dc849c3c576b62803e21482174c39b521
Author: Jim Driscoll <jim.a.driscoll@gmail.com>
Date:   Sun Apr 1 13:20:14 2018 +0100

    Make directory stateful

:040000 040000 0203d59dbb9617026db23831419fdbfa102d9cf2 f3f1d5be6184d4e1cd81768093170ba22b30fb4c M	src

```

**Comment by jj101k** [comment]
This is down to using stateful working directory where it doesn't have an initial state

**Comment by jj101k** [comment]
Fixed - cases like this now need to be a bit more explicit about what to do with global state
