### ISSUE TITLE
Stack size exceeded while examining types

### ISSUE THREAD

**Issue by jj101k** [jj101k/php-lint#61]
```
RangeError: Maximum call stack size exceeded
    at _Mixed.get typeSignature [as typeSignature] (.../src/lib/php-type/mixed.js:22:22)
    at types.map.t (.../src/lib/php-type/union.js:54:42)
    at Array.map (<anonymous>)
    at _Union.get typeSignature [as typeSignature] (.../src/lib/php-type/union.js:54:31)
    at _Union.get typeSignatureToken [as typeSignatureToken] (.../src/lib/php-type/union.js:62:29)
    at _IndexedArray.get typeSignature [as typeSignature] (.../src/lib/php-type/indexed-array.js:22:35)
    at types.map.t (.../src/lib/php-type/union.js:54:42)
    at Array.map (<anonymous>)
    at _Union.get typeSignature [as typeSignature] (.../src/lib/php-type/union.js:54:31)
    at _Union.get typeSignatureToken [as typeSignatureToken] (.../src/lib/php-type/union.js:62:29)
```

**Comment by jj101k** [comment]
Normally this would be completely inadequate as a bug report, but since I can reproduce it trivially it's fine.

**Comment by jj101k** [comment]
Annoyingly, "mixed" is a terminal point so it would have been ok - IOW, it's a deep recursion not an infinite one

**Comment by jj101k** [comment]
Looks like the same union object is entered repeatedly, actually, so yes infinite loop. Probably down to `$x = [$x]` or similar since it's via IndexedArray

**Comment by jj101k** [comment]
Now copies instead
